"""
PDF Report Generator for leads.
Uses reportlab to create a professional PDF of all leads.
"""
import io
from datetime import datetime


def generate_leads_pdf(leads: list, stats: dict) -> bytes:
    """Generate a professional PDF report of leads. Returns PDF bytes."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
        topMargin=1.5*cm, bottomMargin=1.5*cm,
        leftMargin=1.2*cm, rightMargin=1.2*cm)

    styles = getSampleStyleSheet()
    navy   = colors.HexColor("#0d1b2a")
    accent = colors.HexColor("#00c2ff")

    title_style = ParagraphStyle("title", parent=styles["Title"],
        fontSize=22, textColor=navy, spaceAfter=4)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
        fontSize=11, textColor=colors.grey, alignment=TA_CENTER, spaceAfter=16)
    section_style = ParagraphStyle("section", parent=styles["Heading2"],
        fontSize=14, textColor=navy, spaceBefore=12, spaceAfter=8)

    elements = []

    # Header
    elements.append(Paragraph("LeadAI System", title_style))
    elements.append(Paragraph("Leads Database Report", sub_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')} &nbsp;|&nbsp; "
        f"Islamic University of Lebanon — CCE FYP",
        ParagraphStyle("meta", parent=styles["Normal"], fontSize=9,
                       textColor=colors.grey, alignment=TA_CENTER, spaceAfter=20)
    ))

    # Stats summary box
    stats_data = [
        ["Total Leads", "With Email", "Avg Score", "New Leads"],
        [str(stats.get("total", 0)), str(stats.get("with_email", 0)),
         str(stats.get("avg_score", 0)), str(stats.get("new", 0))]
    ]
    stats_table = Table(stats_data, colWidths=[4.3*cm]*4)
    stats_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), navy),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,0), 10),
        ("FONTSIZE", (0,1), (-1,1), 18),
        ("FONTNAME", (0,1), (-1,1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0,1), (-1,1), accent),
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING", (0,0), (-1,-1), 10),
        ("BOTTOMPADDING", (0,0), (-1,-1), 10),
        ("BACKGROUND", (0,1), (-1,1), colors.HexColor("#f7fafc")),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    elements.append(stats_table)
    elements.append(Spacer(1, 20))

    # Leads table
    elements.append(Paragraph(f"All Leads ({len(leads)})", section_style))

    table_data = [["#", "Name", "Email", "Phone", "Platform", "Score", "Status"]]
    for i, lead in enumerate(leads, 1):
        name = (lead.get("name") or "—")[:28]
        email = (lead.get("email") or "—")[:24]
        phone = (lead.get("phone") or "—")[:16]
        table_data.append([
            str(i), name, email, phone,
            lead.get("platform") or "—",
            str(lead.get("score") or 0),
            lead.get("status") or "new"
        ])

    leads_table = Table(table_data, repeatRows=1,
        colWidths=[0.8*cm, 4.2*cm, 4.2*cm, 3*cm, 2.2*cm, 1.3*cm, 1.8*cm])
    leads_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), navy),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,0), 9),
        ("FONTSIZE", (0,1), (-1,-1), 8),
        ("ALIGN", (0,0), (0,-1), "CENTER"),
        ("ALIGN", (5,0), (6,-1), "CENTER"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING", (0,0), (-1,-1), 6),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ("GRID", (0,0), (-1,-1), 0.4, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, colors.HexColor("#f7fafc")]),
    ]))
    elements.append(leads_table)

    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "This report was automatically generated by LeadAI System.",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=8,
                       textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(elements)
    buf.seek(0)
    return buf.getvalue()
